// This file is generated by the 'optics2var' script from the optics file.
// Namespace(dtl='LinacDTL1', end='D204', opt='optics.dat', start='quad1213')

#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <cmath>
#include <complex>
#include <list>
#include <vector>
#include <set>
#include <map>
#include <string>
#include <algorithm>
#include <iterator>
#include <memory>

#include "Exception.h"
#include "FileReport.h"
#include "NameStack.h"
#include "RegMethod.h"
#include "GTKreport.h"
#include "OutputLog.h"
#include "support.h"
#include "stringCombine.h"
#include "MatrixBase.h"
#include "Matrix.h"
#include "Vec3D.h"
#include "Code.h"
#include "varList.h"
#include "FuncDataBase.h"
#include "variableSetup.h"

namespace setVariable
{
void
EssLinacPMQVariables(FuncDataBase &Control)
  /*!
    Create all the PMQ variables
    \param Control :: DataBase
  */
{
  ELog::RegMethod RegA("essVariables[F]","EssLinacPMQVariables");

  Control.addVariable("LinacDTL1PMQ1Length",5);
  Control.addVariable("LinacDTL1PMQ1GapLength",10.2267);
  Control.addVariable("LinacDTL1PMQ2Length",5);
  Control.addVariable("LinacDTL1PMQ2GapLength",10.7922);
  Control.addVariable("LinacDTL1PMQ3Length",5);
  Control.addVariable("LinacDTL1PMQ3GapLength",11.4001);
  Control.addVariable("LinacDTL1PMQ4Length",5);
  Control.addVariable("LinacDTL1PMQ4GapLength",12.0186);
  Control.addVariable("LinacDTL1PMQ5Length",5);
  Control.addVariable("LinacDTL1PMQ5GapLength",12.6467);
  Control.addVariable("LinacDTL1PMQ6Length",5);
  Control.addVariable("LinacDTL1PMQ6GapLength",13.2801);
  Control.addVariable("LinacDTL1PMQ7Length",5);
  Control.addVariable("LinacDTL1PMQ7GapLength",13.9227);
  Control.addVariable("LinacDTL1PMQ8Length",5);
  Control.addVariable("LinacDTL1PMQ8GapLength",14.5767);
  Control.addVariable("LinacDTL1PMQ9Length",5);
  Control.addVariable("LinacDTL1PMQ9GapLength",15.2378);
  Control.addVariable("LinacDTL1PMQ10Length",5);
  Control.addVariable("LinacDTL1PMQ10GapLength",15.9004);
  Control.addVariable("LinacDTL1PMQ11Length",5);
  Control.addVariable("LinacDTL1PMQ11GapLength",16.5756);
  Control.addVariable("LinacDTL1PMQ12Length",5);
  Control.addVariable("LinacDTL1PMQ12GapLength",17.2519);
  Control.addVariable("LinacDTL1PMQ13Length",5);
  Control.addVariable("LinacDTL1PMQ13GapLength",17.9386);
  Control.addVariable("LinacDTL1PMQ14Length",5);
  Control.addVariable("LinacDTL1PMQ14GapLength",18.6271);
  Control.addVariable("LinacDTL1PMQ15Length",5);
  Control.addVariable("LinacDTL1PMQ15GapLength",19.3196);
  Control.addVariable("LinacDTL1PMQ16Length",5);
  Control.addVariable("LinacDTL1PMQ16GapLength",20.0176);
  Control.addVariable("LinacDTL1PMQ17Length",5);
  Control.addVariable("LinacDTL1PMQ17GapLength",20.7118);
  Control.addVariable("LinacDTL1PMQ18Length",5);
  Control.addVariable("LinacDTL1PMQ18GapLength",21.4204);
  Control.addVariable("LinacDTL1PMQ19Length",5);
  Control.addVariable("LinacDTL1PMQ19GapLength",22.1234);
  Control.addVariable("LinacDTL1PMQ20Length",5);
  Control.addVariable("LinacDTL1PMQ20GapLength",22.8328);
  Control.addVariable("LinacDTL1PMQ21Length",5);
  Control.addVariable("LinacDTL1PMQ21GapLength",23.5462);
  Control.addVariable("LinacDTL1PMQ22Length",5);
  Control.addVariable("LinacDTL1PMQ22GapLength",24.256);
  Control.addVariable("LinacDTL1PMQ23Length",5);
  Control.addVariable("LinacDTL1PMQ23GapLength",24.968);
  Control.addVariable("LinacDTL1PMQ24Length",5);
  Control.addVariable("LinacDTL1PMQ24GapLength",25.6916);
  Control.addVariable("LinacDTL1PMQ25Length",5);
  Control.addVariable("LinacDTL1PMQ25GapLength",26.4079);
  Control.addVariable("LinacDTL1PMQ26Length",5);
  Control.addVariable("LinacDTL1PMQ26GapLength",27.1268);
  Control.addVariable("LinacDTL1PMQ27Length",5);
  Control.addVariable("LinacDTL1PMQ27GapLength",27.8447);
  Control.addVariable("LinacDTL1PMQ28Length",5);
  Control.addVariable("LinacDTL1PMQ28GapLength",28.5674);
  Control.addVariable("LinacDTL1PMQ29Length",5);
  Control.addVariable("LinacDTL1PMQ29GapLength",29.2496);
  Control.addVariable("LinacDTL1PMQ30Length",5);
  Control.addVariable("LinacDTL1PMQ30GapLength",29.6263);
  Control.addVariable("LinacDTL1PMQ31Length",5);
  Control.addVariable("LinacDTL1PMQ31GapLength",1);

  Control.addVariable("LinacDTL2PMQ1Length",5);
  Control.addVariable("LinacDTL2PMQ1GapLength",29.908);
  Control.addVariable("LinacDTL2PMQ2Length",8);
  Control.addVariable("LinacDTL2PMQ2GapLength",28.7645);
  Control.addVariable("LinacDTL2PMQ3Length",8);
  Control.addVariable("LinacDTL2PMQ3GapLength",29.4515);
  Control.addVariable("LinacDTL2PMQ4Length",8);
  Control.addVariable("LinacDTL2PMQ4GapLength",30.1815);
  Control.addVariable("LinacDTL2PMQ5Length",8);
  Control.addVariable("LinacDTL2PMQ5GapLength",30.9092);
  Control.addVariable("LinacDTL2PMQ6Length",8);
  Control.addVariable("LinacDTL2PMQ6GapLength",31.6348);
  Control.addVariable("LinacDTL2PMQ7Length",8);
  Control.addVariable("LinacDTL2PMQ7GapLength",32.3564);
  Control.addVariable("LinacDTL2PMQ8Length",8);
  Control.addVariable("LinacDTL2PMQ8GapLength",33.0747);
  Control.addVariable("LinacDTL2PMQ9Length",8);
  Control.addVariable("LinacDTL2PMQ9GapLength",33.7895);
  Control.addVariable("LinacDTL2PMQ10Length",8);
  Control.addVariable("LinacDTL2PMQ10GapLength",34.5005);
  Control.addVariable("LinacDTL2PMQ11Length",8);
  Control.addVariable("LinacDTL2PMQ11GapLength",35.2071);
  Control.addVariable("LinacDTL2PMQ12Length",8);
  Control.addVariable("LinacDTL2PMQ12GapLength",35.9112);
  Control.addVariable("LinacDTL2PMQ13Length",8);
  Control.addVariable("LinacDTL2PMQ13GapLength",36.6108);
  Control.addVariable("LinacDTL2PMQ14Length",8);
  Control.addVariable("LinacDTL2PMQ14GapLength",37.3062);
  Control.addVariable("LinacDTL2PMQ15Length",8);
  Control.addVariable("LinacDTL2PMQ15GapLength",37.9972);
  Control.addVariable("LinacDTL2PMQ16Length",8);
  Control.addVariable("LinacDTL2PMQ16GapLength",38.3937);
  Control.addVariable("LinacDTL2PMQ17Length",8);
  Control.addVariable("LinacDTL2PMQ17GapLength",39.6163);
  Control.addVariable("LinacDTL2PMQ18Length",8);
  Control.addVariable("LinacDTL2PMQ18GapLength",1);

  return;
}
}
    
