// This file is generated by the 'optics2var' script from the optics file.
// Namespace(dtl='LinacDTL1', end='D204US', opt='optics.dat', start='quad1213')
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <cmath>
#include <complex>
#include <list>
#include <vector>
#include <set>
#include <map>
#include <string>
#include <algorithm>
#include <iterator>
#include <memory>

#include "Exception.h"
#include "FileReport.h"
#include "NameStack.h"
#include "RegMethod.h"
#include "GTKreport.h"
#include "OutputLog.h"
#include "support.h"
#include "stringCombine.h"
#include "MatrixBase.h"
#include "Matrix.h"
#include "Vec3D.h"
#include "Code.h"
#include "varList.h"
#include "FuncDataBase.h"
#include "variableSetup.h"
#include "PipeGenerator.h"

namespace setVariable
{
void
EssLinacSpokeVariables(FuncDataBase &Control)
  /*!
    Create all the PMQ variables
    \param Control :: DataBase
  */
{
  ELog::RegMethod RegA("essVariables[F]","EssLinacSpokeVariables");

  // Beam Pipe

  setVariable::PipeGenerator PipeGen;
  PipeGen.setPipe(50.0,0.0);
  PipeGen.setWindow(50.0,0.0);
  PipeGen.setFlange(50.0,0.0);

  double spokeCavityLength = 98.8;
  double quadLength = 25.0;
  
  PipeGen.generatePipe(Control,"LinacSpokeSection0",0.0,76.15);
  Control.addVariable("LinacSpokeSection0VoidMat","Air");

  Control.addVariable("LinacVacuumPipe0Thickness",0.2);
  Control.addVariable("LinacVacuumPipe0VoidMat","Void");
  Control.addVariable("LinacVacuumPipe0Length",76.15);
  Control.addVariable("LinacVacuumPipe0Mat","MARS_STST");
  Control.addVariable("LinacVacuumPipe0InnerRadius",2.801);

  //------------
  for(int i=1;i<13;i++){

    PipeGen.generatePipe(Control,"LinacSpokeSection"+StrFunc::makeString(i*12),0.0,spokeCavityLength);
    Control.addVariable("LinacSpokeSection"+StrFunc::makeString(i*12)+"VoidMat","Air");

    Control.addVariable("LinacSPKCVT"+StrFunc::makeString(i*12)+"Length",spokeCavityLength);
    Control.addVariable("LinacSPKCVT"+StrFunc::makeString(i*12)+"VoidMat","Void");
    Control.addVariable("LinacSPKCVT"+StrFunc::makeString(i*12)+"Thickness",0.4);
    Control.addVariable("LinacSPKCVT"+StrFunc::makeString(i*12)+"Mat","Niobium");

    
    PipeGen.generatePipe(Control,"LinacSpokeSection"+StrFunc::makeString(i*12+1),0.0,14.1);
    Control.addVariable("LinacSpokeSection"+StrFunc::makeString(i*12+1)+"VoidMat","Air");

    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+1)+"Thickness",0.2);
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+1)+"VoidMat","Void");
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+1)+"Length",14.1);
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+1)+"Mat","MARS_STST");
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+1)+"InnerRadius",2.801);
  
    PipeGen.generatePipe(Control,"LinacSpokeSection"+StrFunc::makeString(i*12+2),0.0,spokeCavityLength);
    Control.addVariable("LinacSpokeSection"+StrFunc::makeString(i*12+2)+"VoidMat","Air");
    
    Control.addVariable("LinacSPKCVT"+StrFunc::makeString(i*12+2)+"Length",spokeCavityLength);
    Control.addVariable("LinacSPKCVT"+StrFunc::makeString(i*12+2)+"VoidMat","Void");
    Control.addVariable("LinacSPKCVT"+StrFunc::makeString(i*12+2)+"Thickness",0.4);
    Control.addVariable("LinacSPKCVT"+StrFunc::makeString(i*12+2)+"Mat","Niobium");

  
    PipeGen.generatePipe(Control,"LinacSpokeSection"+StrFunc::makeString(i*12+3),0.0,37.15);
    Control.addVariable("LinacSpokeSection"+StrFunc::makeString(i*12+3)+"VoidMat","Air");

    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+3)+"Thickness",0.2);
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+3)+"VoidMat","Void");
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+3)+"Length",37.15);
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+3)+"Mat","MARS_STST");
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+3)+"InnerRadius",2.801);
    

  
    PipeGen.generatePipe(Control,"LinacSpokeSection"+StrFunc::makeString(i*12+4),0.0,16.0);
    Control.addVariable("LinacSpokeSection"+StrFunc::makeString(i*12+4)+"VoidMat","Air");

    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+4)+"Thickness",0.2);
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+4)+"VoidMat","Void");
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+4)+"Length",16.0);
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+4)+"Mat","MARS_STST");
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+4)+"InnerRadius",2.801);


  
    PipeGen.generatePipe(Control,"LinacSpokeSection"+StrFunc::makeString(i*12+5),0.0,quadLength);
    Control.addVariable("LinacSpokeSection"+StrFunc::makeString(i*12+5)+"VoidMat","Air");
    
    Control.addVariable("LinacQXQuad"+StrFunc::makeString(i*12+5)+"Length",quadLength);
    Control.addVariable("LinacQXQuad"+StrFunc::makeString(i*12+5)+"VoidMat","Void");
    Control.addVariable("LinacQXQuad"+StrFunc::makeString(i*12+5)+"Thickness",0.2);
    Control.addVariable("LinacQXQuad"+StrFunc::makeString(i*12+5)+"PipeMat","MARS_STST");
    Control.addVariable("LinacQXQuad"+StrFunc::makeString(i*12+5)+"YokeMat","MARS_QXYOKE");
    Control.addVariable("LinacQXQuad"+StrFunc::makeString(i*12+5)+"CoilMat","MARS_QXCOIL"); 
 
    PipeGen.generatePipe(Control,"LinacSpokeSection"+StrFunc::makeString(i*12+6),0.0,12.0);
    Control.addVariable("LinacSpokeSection"+StrFunc::makeString(i*12+6)+"VoidMat","Air");

    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+6)+"Thickness",0.2);
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+6)+"VoidMat","Void");
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+6)+"Length",12.0);
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+6)+"Mat","MARS_STST");
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+6)+"InnerRadius",2.801);
    
    PipeGen.generatePipe(Control,"LinacSpokeSection"+StrFunc::makeString(i*12+7),0.0,46.0);
    Control.addVariable("LinacSpokeSection"+StrFunc::makeString(i*12+7)+"VoidMat","Air");


    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+7)+"Thickness",0.2);
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+7)+"VoidMat","Void");
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+7)+"Length",46.0);
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+7)+"Mat","MARS_STST");
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+7)+"InnerRadius",2.801);

  
    PipeGen.generatePipe(Control,"LinacSpokeSection"+StrFunc::makeString(i*12+8),0.0,quadLength);
    Control.addVariable("LinacSpokeSection"+StrFunc::makeString(i*12+8)+"VoidMat","Air");

    Control.addVariable("LinacQXQuad"+StrFunc::makeString(i*12+8)+"Length",quadLength);
    Control.addVariable("LinacQXQuad"+StrFunc::makeString(i*12+8)+"VoidMat","Void");
    Control.addVariable("LinacQXQuad"+StrFunc::makeString(i*12+8)+"Thickness",0.2);
    Control.addVariable("LinacQXQuad"+StrFunc::makeString(i*12+8)+"PipeMat","MARS_STST");
    Control.addVariable("LinacQXQuad"+StrFunc::makeString(i*12+8)+"YokeMat","MARS_QXYOKE");
    Control.addVariable("LinacQXQuad"+StrFunc::makeString(i*12+8)+"CoilMat","MARS_QXCOIL"); 

  
    PipeGen.generatePipe(Control,"LinacSpokeSection"+StrFunc::makeString(i*12+9),0.0,16.0);
    Control.addVariable("LinacSpokeSection"+StrFunc::makeString(i*12+9)+"VoidMat","Air");
    
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+9)+"Thickness",0.2);
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+9)+"VoidMat","Void");
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+9)+"Length",16.0);
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+9)+"Mat","MARS_STST");
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+9)+"InnerRadius",2.801);

 
    PipeGen.generatePipe(Control,"LinacSpokeSection"+StrFunc::makeString(i*12+10),0.0,37.15);
    Control.addVariable("LinacSpokeSection"+StrFunc::makeString(i*12+10)+"VoidMat","Air");

    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+10)+"Thickness",0.2);
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+10)+"VoidMat","Void");
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+10)+"Length",37.15);
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+10)+"Mat","MARS_STST");
    Control.addVariable("LinacVacuumPipe"+StrFunc::makeString(i*12+10)+"InnerRadius",2.801);

    

  }

  PipeGen.generatePipe(Control,"LinacSpokeSection155",0.0,spokeCavityLength);
  Control.addVariable("LinacSpokeSection155VoidMat","Air");
  
  Control.addVariable("LinacSPKCVT155Length",spokeCavityLength);
  Control.addVariable("LinacSPKCVT155VoidMat","Void");
  Control.addVariable("LinacSPKCVT155Thickness",0.4);
  Control.addVariable("LinacSPKCVT155Mat","Niobium");
  
    
  PipeGen.generatePipe(Control,"LinacSpokeSection156" ,0.0,14.1);
  Control.addVariable("LinacSpokeSection156VoidMat","Air");
  
  Control.addVariable("LinacVacuumPipe156Thickness",0.2);
  Control.addVariable("LinacVacuumPipe156VoidMat","Void");
  Control.addVariable("LinacVacuumPipe156Length",14.1);
  Control.addVariable("LinacVacuumPipe156Mat","MARS_STST");
  Control.addVariable("LinacVacuumPipe156InnerRadius",2.801);
  
  PipeGen.generatePipe(Control,"LinacSpokeSection157" ,0.0,spokeCavityLength);
  Control.addVariable("LinacSpokeSection157VoidMat","Air");
  
  Control.addVariable("LinacSPKCVT157Length",spokeCavityLength);
  Control.addVariable("LinacSPKCVT157VoidMat","Void");
  Control.addVariable("LinacSPKCVT157Thickness",0.4);
  Control.addVariable("LinacSPKCVT157Mat","Niobium");
    



  
  return;
}
}
    
