# test of travis ci for comblayer
language: cpp
matrix:
   include:
    # linux - g++ 5
     - os: linux
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
             - george-edison55-precise-backports
           packages:
             - g++-5
             - cmake
             - cmake-data
             - libgsl0-dev
             - libboost-dev
             - libboost-regex-dev
             - libboost-filesystem-dev
       env:
          - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    # linux - g++ 7
     - os: linux
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
             - george-edison55-precise-backports
           packages:
             - g++-7
             - cmake
             - cmake-data
             - libgsl0-dev
             - libboost-dev
             - libboost-regex-dev
             - libboost-filesystem-dev
       env:
          - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
   # linux - clang 5.0 with g++6
     - os: linux
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
             - llvm-toolchain-trusty-5.0
             - george-edison55-precise-backports
           packages:
             - g++-6
             - clang-5.0
             - cmake
             - cmake-data
             - libgsl0-dev
             - libboost-dev
             - libboost-regex-dev
             - libboost-filesystem-dev
       env:
          - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
before_install:
  - eval "${MATRIX_EVAL}" 
  - cmake -version
  - echo $CC
  - echo $CXX 
script:
  - ./CMake.pl -O -g++=$CXX
  - cmake ./
  - make -j6
  # unit test
  - ./testMain -1 -1 -1
  # model quick tests
  - ./fullBuild -r fb_test 
  - ./ess -r ess_test
  - ./bilbau -r bb_test
  - ./sns -r sns_test
  - ./reactor -r reactor_test
  - ./muBeam -r mu_test
  - ./pipe -r pipe_test
  - ./maxiv --defaultConfig Single BALDER balder_test
  - ./singleItem -r single_test
  - ./t1MarkII -r t1_test1
  - ./t1Real -r t1_test2 
  # model valid check
  - ./fullBuild -r -validCheck 100000 fb_vtest
  - ./maxiv --defaultConfig Single BALDER -validCheck 100000 ba_vtest
  - ./testMain -1 -1 -1
 
  



  
