# test of travis ci for comblayer
language: cpp
dist: trusty
matrix:
   include:
   # linux
     - os: linux
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
	     - g++-7
             - cmake
             - cmake-data
             - libgsl0-dev
             - libboost-dev
             - libboost-regex-dev
             - libboost-filesystem-dev
       env:
          - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#	  - LINKER_FLAGS=""
     - os: linux
       addons:
        apt:
           sources:
	     - ubuntu-toolchain-r-test
             - llvm-toolchain-trusty-6.0
             - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
               key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
           packages:
	     - clang-6.0
             - libstdc++6
	     - cmake
             - cmake-data
             - libgsl0-dev
             - libboost-dev
             - libboost-regex-dev
             - libboost-filesystem-dev
    env:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - LINKER_FLAGS="-stdlib=libc++ -lc++abi"

before_install:
  - eval "${MATRIX_EVAL}"
  - cmake -version
  - echo $CC
  - echo $CXX
script:
  - ./CMake.pl -O -g++=$CXX
  - cmake ./
  - make -j6
  # unit test
  # - ./testMain -1 -1 -1
  # model quick tests
  # - ./fullBuild -r fb_test
  # - ./ess -r ess_test
  # - ./bilbau -r bb_test
  # - ./sns -r sns_test
  # - ./reactor -r reactor_test
  # - ./muBeam -r mu_test
  # - ./pipe -r pipe_test
  # - ./maxiv --defaultConfig Single BALDER balder_test
  # - ./singleItem -r single_test
  # - ./t1MarkII -r t1_test1
  # - ./t1Real -r t1_test2
  # # model valid check
  # - ./fullBuild -r -validCheck 100000 fb_vtest
  # - ./maxiv --defaultConfig Single BALDER -validCheck 100000 ba_vtest
  # - ./testMain -1 -1 -1
  - ./maxiv -r -defaultConfig LINAC All a
