# test of travis ci for comblayer
language: cpp
matrix:
   include:
    # linux - g++ 5
     - os: linux
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
             - george-edison55-precise-backports
           packages:
             - g++-5
             - cmake
             - cmake-data
             - libgsl0-dev
             - libboost-dev
             - libboost-regex-dev
             - libboost-filesystem-dev
       env:
          - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    # linux - g++ 7
     - os: linux
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
             - george-edison55-precise-backports
           packages:
             - g++-7
             - cmake
             - cmake-data
             - libgsl0-dev
             - libboost-dev
             - libboost-regex-dev
             - libboost-filesystem-dev
       env:
          - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
     # linux - clang 3.7 with default g++
     - os: linux
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
             - llvm-toolchain-precise-3.7
             - george-edison55-precise-backports
           packages:
             - clang-3.7
             - cmake
             - cmake-data
             - libgsl0-dev
             - libboost-dev
             - libboost-regex-dev
             - libboost-filesystem-dev
       env:
          - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"
    # linux - clang 5.0 with g++6
     - os: linux
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
             - llvm-toolchain-trusty-5.0
             - george-edison55-precise-backports
           packages:
             - g++-6
             - clang-5.0
             - cmake
             - cmake-data
             - libgsl0-dev
             - libboost-dev
             - libboost-regex-dev
             - libboost-filesystem-dev
       env:
          - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
before_install:
  - eval "${MATRIX_EVAL}" 
  - cmake -version
  - echo $CC
  - echo $CXX 
script:
  - ./CMake.pl -O -g++=$CXX
  - cmake ./
  - make -j6
  # unit test
  - ./testMain -1 -1 -1
  # model quick tests
  - ./fullBuild -r fb_test 
  - ./bilbau -r bb_test
  - ./sns -r sns_test
  - ./reactor -r reactor_test
  - ./muBeam -r mu_test
  - ./pipe -r pipe_test
  - ./balder -r balder_test
  - ./balder -r -validCheck 100000 ba_vtest
  - ./singleItem -r single_test
  - ./t1MarkII -r t1_test1
  - ./t1Real -r t1_test2
  # model valid check
  - ./fullBuild -r -validCheck 100000 fb_vtest
  - ./ess -eng -topMod Pancake -lowMod None -validCheck 100000 pc-eng-test
  - ./ess      -topMod Pancake -lowMod None -validCheck 100000 pc-test
  - ./ess -eng -topMod Box     -lowMod None -validCheck 100000 box-eng-test
  - ./ess      -topMod Box     -lowMod None -validCheck 100000 box-test
  - ./ess -eng -topMod BF1     -lowMod None -validCheck 100000 bf1-single-eng-test
  - ./ess      -topMod BF1     -lowMod None -validCheck 100000 bf1-single-test
  - ./ess -eng -topMod BF2     -lowMod None -validCheck 100000 bf2-single-eng-test
  - ./ess      -topMod BF2     -lowMod None -validCheck 100000 bf2-single-test
  - ./ess -eng -topMod BF1     -lowMod BF1  -validCheck 100000 bf1-eng-test
  - ./ess      -topMod BF1     -lowMod BF1  -validCheck 100000 bf1-test
  - ./ess -eng -topMod BF2     -lowMod BF2  -validCheck 100000 bf2-eng-test
  - ./ess      -topMod BF2     -lowMod BF2  -validCheck 100000 bf2-test
  - ./ess -eng -topMod BF2     -lowMod BF1  -validCheck 100000  -r BilbaoWheel bf2-bf1-test
  - ./ess      -topMod BF2     -lowMod BF1  -validCheck 100000  -r BilbaoWheel bf2-bf1-test
  - ./ess -eng -topMod BF1     -lowMod BF2  -validCheck 100000 bf2-bf1-test
  - ./ess      -topMod BF1     -lowMod BF2  -validCheck 100000 bf2-bf1-test
  - ./ess -r -defaultConfig Single NMX -bunker void -v TargetTopClearanceHeight 2 --validCheck 100000 a
  - ./ess -r -eng -defaultConfig Single CSPEC VOR --validCheck 10000 a
  - ./ess -r -eng -defaultConfig Single NMX G1BLineTop3 VOR --validCheck 10000 b
